module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'infra',
        'security',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'common',
        'gateway',
        'auth',
        'catalog',
        'cart',
        'order',
        'payment',
        'inventory',
        'notification',
        'monitoring',
        'docker',
        'ci',
        'deps',
        'root',
      ],
    ],
    'header-max-length': [2, 'always', 100],
  },
};
