// ═══════════════════════════════════════════════════
// Centralized Error Codes
// Used across ALL services for consistent error responses
// Format: DOMAIN_SPECIFIC_ERROR
// ═══════════════════════════════════════════════════

export const ErrorCodes = Object.freeze({
  // --- Generic ---
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',

  // --- Authentication ---
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_NOT_VERIFIED: 'AUTH_ACCOUNT_NOT_VERIFIED',

  // --- User ---
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',

  // --- Catalog ---
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',

  // --- Cart ---
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_EMPTY: 'CART_EMPTY',
  CART_QUANTITY_EXCEEDED: 'CART_QUANTITY_EXCEEDED',

  // --- Inventory ---
  INVENTORY_INSUFFICIENT_STOCK: 'INVENTORY_INSUFFICIENT_STOCK',
  INVENTORY_RESERVATION_FAILED: 'INVENTORY_RESERVATION_FAILED',
  INVENTORY_RESERVATION_EXPIRED: 'INVENTORY_RESERVATION_EXPIRED',
  INVENTORY_LOCK_FAILED: 'INVENTORY_LOCK_FAILED',

  // --- Order ---
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
  ORDER_PAYMENT_REQUIRED: 'ORDER_PAYMENT_REQUIRED',

  // --- Payment ---
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
  PAYMENT_INVALID_WEBHOOK: 'PAYMENT_INVALID_WEBHOOK',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',

  // --- Notification ---
  NOTIFICATION_DELIVERY_FAILED: 'NOTIFICATION_DELIVERY_FAILED',
  NOTIFICATION_TEMPLATE_NOT_FOUND: 'NOTIFICATION_TEMPLATE_NOT_FOUND',
});